### ISSUE TITLE
yarn build-export fails while compiling SCSS

### ISSUE THREAD

**Issue by mstudio** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-template#124]
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template/blob/1dac8a9dc33ddd73acf0d4eec5f768431082625e/package.json#L20

When I run `yarn build-export`, I'm seeing a build error for SASS. 
Can we please update `build-export` in `package.json` to include SASS_PATH, as it's done with `build`?
```
"build-export": "cross-env SASS_PATH=node_modules:src next build && next export",
```
Thanks

**Comment by emyarod** [comment]
I think we typically expect these environment variables to be set on the user's end, which also follows the convention we have across our projects https://www.ibm.com/standards/carbon/developing/web-components-tutorial/step-1/#install-and-build-sass

**Comment by jeffchew** [comment]
Closing this, this can be adjusted on the application side.
