### ISSUE TITLE
Country selector in footer does not show all altlang entries

### ISSUE THREAD

**Issue by flatcoding** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-template#15]
The country selector only shows a subset of the cc-lc entries in altlang.json.

## Detailed description

This is my altlang.json
`[
  {
    "lc": "fr",
    "cc": "fr"
  },
  {
    "lc": "en",
    "cc": "cz"
  },
  {
    "lc": "de",
    "cc": "at"
  },
  {
    "lc": "de",
    "cc": "ch"
  },
  {
    "lc": "de",
    "cc": "de"
  },
  {
    "lc": "en",
    "cc": "dk"
  },
  {
    "lc": "en",
    "cc": "ie"
  },
  {
    "lc": "es",
    "cc": "es"
  },
  {
    "lc": "pl",
    "cc": "pl"
  },
  {
    "lc": "it",
    "cc": "it"
  },
  {
    "lc": "en",
    "cc": "no"
  },
  {
    "lc": "en",
    "cc": "se"
  },
  {
    "lc": "en",
    "cc": "fi"
  },
  {
    "lc": "en",
    "cc": "be"
  },
  {
    "lc": "en",
    "cc": "nl"
  },
  {
    "lc": "en",
    "cc": "gb"
  }
]`

It does show the first 9 entries on the web page, in the footer country selector, but ignores the others. Seems like it 'breaks' at some point in the list. If I insert a new proper entry inbetween, it could be that it is shown as well, but could also be breaking at that step then.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Probably a bug

> Is this issue related to a specific component?

Yes, Footer --> country selector

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected to see all country / language combinations available, at least where cc and lc have reasonable values.

> What browser are you working in?

FF / Chrome latest

> What version of the NextJS template are you using?

Not sure, I don't see any version numbering... we started in July though, and using e.g. @carbon/ibmdotcom-react": "^1.11.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Storage Digital Platform - this is already live and having quite some attention. This is a smaller annoying bug. Doesn't break, but makes switching between locales quite difficult here and there.

## Steps to reproduce the issue
1. Go e.g. here https://wwwstage.ibm.com/it-infrastructure/storage/flash/offers/uk-en
2. Enter user name and password if prompted (enter once, then hit cancel)
3. Scroll to bottom, click on 'United Kingdom - English' in the footer country selector. Click on Europe
4. Note that it contains less entries than my list above.

**Comment by flatcoding** [comment]
Didn't realize this is public github. Can contact me internally as well if any questions: erik.reder@de.ibm.com

**Comment by RobertaJHahn** [comment]
Meeting info:  Severity 2, assign to next sprint and no release.

**Comment by jeffchew** [comment]
@flatcoding we merged in a number of changes that may have resolved this, can you pull latest changes from the template and see?

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template#upgrading-from-the-template

cc: @annawen1

**Comment by flatcoding** [comment]
Thx for the support, will have a look!

**Comment by flatcoding** [comment]
And a big thanks again, @annawen1 , we were able to apply several updates and the footer is now working well for us!
