### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by alexanderbartels** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-template#2]
Hi, thanks for the template!
we want to build a site for ibm.com using this template. But one question i have is how to support different locales with static export. 

if i clone this template and run `yarn build-export` it generates a single index.html file. Is there any recommendation on how to add i18n to the site?

I would really like to use a static export to host the site as we want to communicate against a REST API, but if not possible i think it would also be ok to run a nodejs instance. 

I haven't found anything regarding i18n in the official next.js documentation. 

Thanks,
Alex

**Comment by jeffchew** [comment]
@alexanderbartels apologies for the late reply on this! I'm actually going to convert this to a `feature request` as our team would like to think about how to safely incorporate a multi-lingual solution and how that dove tails with the IBM locale selector. At this moment, the NextJS template sets the country/language combination via query parameters, but will see what is the best way to integrate with multi language content.

cc: @RobertaJHahn @ljcarot

**Comment by alexanderbartels** [comment]
short update about our request. In the meantime we had to switch to the server-side rendered version instead of the static export one. This allowed us to use the i18next module for next.js (`next-i18next`). It works somehow: https://www.ibm.com/it-infrastructure/storage/flash/offers/uk-en

but we have some trouble with it, so it would still be great to have a built-in solution that works for the ibm.com sites :) 

Thanks 🍻

**Comment by jeffchew** [comment]
Thanks for the update @alexanderbartels ! We'll definitely put that into consideration, and we have already seen differences in implementation between static generated and served via node (and limitations of the former approach). We might even consider supporting two separate templates depending on the approach, but that's still a bit early to decide.

cc: @annawen1 @kennylam @asudoh @RaphaelAmadeu @andysherman2121
