### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by Kieran-Muller-Ent** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-template#32]
## Detailed description

> Describe in detail the issue you're having.
When running ```yarn dev``` on the un-modified repo and going to the localhost route I receive an error. See Additional information. Error seems to be from by axios.

I am using google chrome and I believe I am on the latest version of the template (I have pulled the latest version and yarn upgraded incase that helped)

## Steps to reproduce the issue

1. clone the repo
2. yarn
3. yarn dev
4. go to http://localhost:3000
5. unhandled runtime error

## Additional information

![Screenshot 2021-01-28 at 09 02 44](https://user-images.githubusercontent.com/57447348/106115055-3c2c2e00-6148-11eb-948c-2237669d26fc.png)

**Comment by annawen1** [comment]
@Kieran-Muller-Ent we made an update to our services package to address this issue, what you can do for now is pull in the canary versions of @carbon/ibmdotcom-react and @carbon/ibmdotcom-styles. We do have our v1.16.0 release coming up at the end of this month

**Comment by Kieran-Muller-Ent** [comment]
@annawen1 Awesome! Thanks for letting me know. Looking forward to the next release :D

**Comment by RobertaJHahn** [comment]
Closing, based on comments above.
