### ISSUE TITLE
Blocker - Cannot run build on NextJS template

### ISSUE THREAD

**Issue by Claire-ibm-toulouse** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-template#34]
I want to deploy my application (uses a NextJs template) but I am getting this error:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/74964904/108859593-aae89400-75ed-11eb-8ecb-53687d9a10ed.png">
(using yarn build-export)

I tried to deploy the template itself (without any updates by me) and I am getting the same error:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/74964904/108859794-dff4e680-75ed-11eb-9289-4c1a6d0f77bb.png">
(using npm run build)

**Comment by kennylam** [comment]
Issue has been resolved. It seems running some of the initial build steps out of order will produce this error. Followup is to update the repo intro to properly document the steps needed for the initial build.
