### ISSUE TITLE
Tag Management Script is loaded twice

### ISSUE THREAD

**Issue by fabianklonsdorf** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-template#37]
## Detailed description

> When working with the Next.JS Template and including the `<script src="//1.www.s81c.com/common/stats/ibm-common.js" defer></script>` the script is loaded twice due to an existing Next.js issue: https://github.com/vercel/next.js/issues/9070

 
> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
No

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The script should only be loaded once and there shouldn't be an error in dev environment.

> What browser are you working in?
Firefox, Chrome, Safari

> What version of the NextJS template are you using?
9.5.5

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM CHQ Events // DACH

## Steps to reproduce the issue

1. Open a Website using Next.js (e.g. Think)
2. Open the console
3. See the errors

## Additional information

![Screenshot 2021-03-17 at 17 53 52](https://user-images.githubusercontent.com/47037236/111506994-7e3a1f00-874a-11eb-91e1-ea396f1ac6ed.png)
![Screenshot 2021-03-17 at 17 54 22](https://user-images.githubusercontent.com/47037236/111507000-7f6b4c00-874a-11eb-9e40-78ed71f8672c.png)
![Screenshot 2021-03-17 at 17 54 31](https://user-images.githubusercontent.com/47037236/111507003-8003e280-874a-11eb-9ac4-5e91835bdd00.png)

**Comment by RobertaJHahn** [comment]
Fix was found, but need to be applied.  Anna to provide link.
