### ISSUE TITLE
[Card in card] Transition animation bug

### ISSUE THREAD

**Issue by fabianklonsdorf** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-template#39]
## Detailed description

> Describe in detail the issue you're having.
Card in Card Transition is different. The Image does have the correct transition and the card in the card (text card) does not have a transition.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
http://ibmdotcom-web-components.mybluemix.net/?path=/story/components-card-in-card--default

> What did you expect to happen? What happened instead? What would you like to
> see changed?
http://ibmdotcom-web-components.mybluemix.net/?path=/story/components-card-in-card--default should have a transition in the text card: transition: 150ms cubic-bezier(0.2, 0, 0.38, 0.9);

> What browser are you working in?
Firefox latest version

> What version of the NextJS template are you using?
-

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
-

## Steps to reproduce the issue

1. Step one
Go to card in card section in storybook
2. Step two
Hover
3. Step three
See the glitch
4. etc.

## Expecting (Updated Jun 25 by Shixie)

Card in card's hover animation should follow the following spec:

| White & Gray 10 themes | Gray 90 and Gray 100 themes |
| --- | --- |
| `darken: 8%` | `lighten: 8%` |

Transition easing & duration should match the current text portion background change: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/ea01b1b2-a073-44dd-a62f-fbafd7efc13d)

**Comment by DragosRistici** [comment]
## More information received

### What one sees 
https://user-images.githubusercontent.com/48327647/112834634-e4a33380-90a0-11eb-86e8-06bd1eba1a9b.mov

### What one should see
https://user-images.githubusercontent.com/48327647/112834656-ebca4180-90a0-11eb-812c-050555fbb153.mov

### What seems to be missing
![Expected](https://user-images.githubusercontent.com/48327647/112834661-ec62d800-90a0-11eb-875d-a39028d7cff8.png)
