### ISSUE TITLE
Update nextjs to 10.0.5 or above

### ISSUE THREAD

**Issue by joscorga** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-template#42]
### The problem

While trying to use a nextjs feature (with the version configured on this template) which allows applications to override the base path, it works on development mode but when trying on production mode it does not.

I found this issue vercel/next.js#20097 and they mentioned it was fixed in a more recent version so I updated to 10.0.5 (not the latest) and found out indeed the issue is resolved.

### The solution

Please update your template to support a more recent version of next.js.

**Comment by jeffchew** [comment]
@RobertaJHahn can this be added to our next refinement meeting?

cc: @annawen1
