### ISSUE TITLE
[Carousel] react wrapper - not loading properly on page load

### ISSUE THREAD

**Issue by guiruann** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-template#53]
## Detailed description

> Describe in detail the issue you're having.
On page load, the styling for the Carousel component takes a couple seconds to load.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
This is a bug.

> Is this issue related to a specific component?
Yes, to the Carousel component from 'Carbon for IBM.com Web Components with React'. https://ibmdotcom-web-components-react.mybluemix.net/?path=/story/components-carousel--default

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expected that the component would load properly once page is loaded, but what happens is that its styling does not load for a couple of seconds. I would like to see its styling fully loading.

> What browser are you working in?
Google Chrome Version 90.0.4430.212

> What version of the NextJS template are you using?
10.1.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
In this case, I'm working on [ibm.com/events](https://www.ibm.com/events). No release dates.

## Steps to reproduce the issue

1. Step one
Include [Carousel component ](https://ibmdotcom-web-components-react.mybluemix.net/?path=/story/components-carousel--default) on a project using NextJS template.

2. Step two
Run `yarn build-export` to generate build files.

3. Step three
Upload build files to testing/production environment.

## Additional information

- Screenshots or code

https://user-images.githubusercontent.com/51061825/119657999-056ad980-be03-11eb-9538-eb458b94a7af.mov

- Notes
This issue only seems to happen when I upload the build files to wwwpreview or wwwstage. On localhost it seems to be working properly. The issue can be seen on this wwwpreview page: https://wwwpreview.ibm.com/events/

**Comment by RobertaJHahn** [comment]
This issue has been fixed for the adopter.  The NextJS template has to be fixed.

**Comment by andysherman2121** [comment]
`window-or-global.readyState === 'interactive' || window-or-global.readyState === 'complete'`

We have to use `window-or-global` There’s an example here with how we use it. https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/react/src/components/Masthead/Masthead.js#L25

packages/react/src/components/Masthead/Masthead.js:25
